- name: Install CLI tools from apt
  apt:
    name:
      - tmux
      - btop
      - lsd
      - fzf
      - fd-find
      - ripgrep
      - bat
      - trash-cli
      - nautilus
      - jq
      - zip
      - unzip
      - gh
      - gdu
      - tokei
    state: present
  become: true

- name: Symlink fdfind to fd in ~/.local/bin
  file:
    src: /usr/bin/fdfind
    dest: "{{ bin_dir }}/fd"
    state: link
