- name: Install cargo tools
  community.general.cargo:
    name:
      - zoxide
      - yazi-build
      - impala
      - bluetui
  handlers:
    - name: Install yazi packages
      command: ya pkg install
