- name: Check if nvim is installed
  stat:
    path: /usr/local/bin/nvim
  register: nvim_binary

- name: Install nvim build dependencies
  apt:
    name:
      - g++
      - cmake
      - curl
      - unzip
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - pkg-config
    state: present
  become: true
  when: not nvim_binary.stat.exists

- name: Clone neovim repository
  git:
    repo: https://github.com/neovim/neovim
    dest: "{{ ansible_env.HOME }}/github/neovim"
    clone: true
    depth: 1
    version: master
  when: not nvim_binary.stat.exists

- name: Build nvim release version
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/github/neovim"
    params:
      CMAKE_BUILD_TYPE: Release
  when: not nvim_binary.stat.exists

- name: Install nvim release version
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/github/neovim"
    target: install
  become: true
  when: not nvim_binary.stat.exists
