- name: Download wezterm GPG key
  get_url:
    url: https://apt.fury.io/wez/gpg.key
    dest: /tmp/wezterm-gpg.key
    mode: "0644"
  changed_when: false

- name: Convert and install GPG key
  command: gpg --dearmor -o /usr/share/keyrings/wezterm-fury.gpg /tmp/wezterm-gpg.key
  args:
    creates: /usr/share/keyrings/wezterm-fury.gpg
  become: true

- name: Set permissions for GPG key
  file:
    path: /usr/share/keyrings/wezterm-fury.gpg
    mode: "0644"
  become: true

- name: Add wezterm repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    filename: wezterm
    state: present
  become: true

- name: Install wezterm
  apt:
    name: wezterm
    state: present
    update_cache: true
  become: true
