- name: Download wezterm GPG key
  get_url:
    url: https://apt.fury.io/wez/gpg.key
    dest: /tmp/wezterm-gpg.key
    mode: "0644"

- name: Convert and install GPG key
  shell: gpg --dearmor < /tmp/wezterm-gpg.key > /usr/share/keyrings/wezterm-fury.gpg
  args:
    creates: /usr/share/keyrings/wezterm-fury.gpg
  become: true

- name: Add wezterm repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    filename: wezterm
    state: present
  become: true

- name: Install wezterm
  apt:
    name: wezterm
    state: present
    update_cache: true
  become: true
