- name: Install dependencies
  apt:
    name:
      - autoconf
      - gcc
      - make
      - pkg-config
      - libpam0g-dev
      - libcairo2-dev
      - libfontconfig1-dev
      - libxcb-composite0-dev
      - libev-dev
      - libx11-xcb-dev
      - libxcb-xkb-dev
      - libxcb-xinerama0-dev
      - libxcb-randr0-dev
      - libxcb-image0-dev
      - libxcb-util0-dev
      - libxcb-xrm-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libjpeg-dev
      - libgif-dev
    state: present
  become: true

- name: Clone i3lock-color
  git:
    repo: "https://github.com/Raymo111/i3lock-color.git"
    dest: "{{ xdg_data_home }}/i3lock-color"
    version: master

- name: Build and Install i3lock-color
  command: ./install-i3lock-color.sh
  args:
    chdir: "{{ xdg_data_home }}/i3lock-color"
    creates: /usr/bin/i3lock
  become: true

- name: Install betterlockscreen
  shell: wget https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/main/install.sh -O - -q | bash -s system
  args:
    creates: /usr/local/bin/betterlockscreen
  become: true
  notify: update betterlockscreen
