- name: Include apt-based GUI apps
  include_tasks: apt.yml

- name: Include flatpak GUI apps
  include_tasks: flatpak.yml

- name: Include JetBrains Toolbox installation
  include_tasks: jetbrains.yml

- name: Include Proton VPN installation
  include_tasks: protonvpn.yml
